language: python
python:  
  - "3.6" 

install:
  - pip install -r ./requirements.txt
  - pip install coverage
  - pip install coveralls
  
script:
  - coverage run --source= '.'/v2/tests 
  - coverage -report
  
after_success:
  - coveralls