language: python
python:  
  - "3.6" 

install:
  - pip install -r requirements.txt
  - pip install nose2
  - pip install coveralls
  
script:
 - nosetests --with-coverage --cover-package= ./v2/tests/ 
  
after_success:
  - coveralls
